In [3]:
import pandas as pd
from io import StringIO
import logging
import geopandas as gpd

In [38]:
# NYC FIPS CODES TO CONSOLIDATE INTO NYC GEOGRAPHY
NYC_FIPS = ["36061", "36005", "36081", "36047", "36085"]

In [10]:
def clean_fips(fips):
    if pd.isnull(fips):
        return "-1"
    else:
        return ("00000" + str(int(fips)))[-5:]

In [51]:
TRI_STATE = ["09", "34", "36"]
NORTHEAST = ["25", "00", "33", "34", "36", "42", "50", "09", "23", "44"]

In [47]:
class Shapefile:
    def __init__(
        self, file_name: str, lat_col: str = "INTPTLAT", lng_col: str = "INTPTLON"
    ):
        shapefile = gpd.read_file(file_name)
        # convert lat and long to decimal
        shapefile.loc[:, "INTPTLAT"] = shapefile.INTPTLAT.apply(lambda x: float(x[1:]))
        shapefile.loc[:, "INTPTLON"] = shapefile.INTPTLON.apply(float)
        self.shapefile = shapefile
        self.file_name = file_name

    def continental_us(self):
        self.shapefile = self.shapefile.loc[
            (self.shapefile["INTPTLAT"] > 25)
            & (self.shapefile["INTPTLON"] < 0)
            & (self.shapefile["INTPTLON"] > -130)
        ]
        return self.shapefile

    def filter_geography(self, state_fp_list):
        return self.shapefile.loc[self.shapefile.STATEFP.isin(state_fp_list)]

In [56]:
class CountyShapefile(Shapefile):
    def __init__(self, file_name):
        super().__init__(file_name)
        self.shapefile.loc[:, "fips"] = self.shapefile.GEOID.apply(
            lambda x: "00000" if x in NYC_FIPS else x
        )

        # MAKE NYC into a single geography
        self.shapefile = self.shapefile.dissolve(by="fips")

        self.shapefile.reset_index(inplace=True)

In [53]:
CountyShapeFile(file_name="shapefile/tl_2019_us_county/tl_2019_us_county.shp").filter_geography(TRI_STATE)

,fips,geometry,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON
0,00000,"MULTIPOLYGON (((-74.25909 40.49956, -74.25909 ...",36,085,00974141,36085,Richmond,Richmond County,06,H6,G4020,408,35620,35614,C,148976885,115948458,40.561263,-74.139899
309,09001,"POLYGON ((-73.54362 41.37509, -73.54347 41.376...",09,001,00212794,09001,Fairfield,Fairfield County,06,H4,G4020,408,14860,None,N,1618659464,549285481,41.227413,-73.367061
310,09003,"POLYGON ((-72.94902 41.80643, -72.94894 41.806...",09,003,00212338,09003,Hartford,Hartford County,06,H4,G4020,278,25540,None,N,1903543898,40543777,41.806053,-72.732916
311,09005,"POLYGON ((-73.50793 41.79152, -73.50787 41.792...",09,005,00212796,09005,Litchfield,Litchfield County,06,H4,G4020,408,45860,None,N,2384120288,62342856,41.791883,-73.235404
312,09007,"POLYGON ((-72.65367 41.43812, -72.65419 41.438...",09,007,00212797,09007,Middlesex,Middlesex County,06,H4,G4020,278,25540,None,N,956493754,180679140,41.433003,-72.522780
313,09009,"POLYGON ((-73.14755 41.36770, -73.14852 41.368...",09,009,00212798,09009,New Haven,New Haven County,06,H4,G4020,408,35300,None,N,1565683007,667074958,41.349719,-72.900203
314,09011,"POLYGON ((-72.32451 41.61857, -72.32467 41.618...",09,011,00212799,09011,New London,New London County,06,H4,G4020,278,35980,None,N,1722711022,276663467,41.472652,-72.108634
315,09013,"POLYGON ((-72.49681 41.86062, -72.50104 41.859...",09,013,00212668,09013,Tolland,Tolland County,06,H4,G4020,278,25540,None,N,1062807466,17549693,41.858081,-72.340978
316,09015,"POLYGON ((-72.16450 41.83491, -72.16456 41.834...",09,015,00212801,09015,Windham,Windham County,06,H4,G4020,148,49340,None,N,1328478482,21477921,41.824999,-71.990702
1775,34001,"POLYGON ((-74.85675 39.42076, -74.85670 39.420...",34,001,00882270,34001,Atlantic,Atlantic County,06,H1,G4020,428,12100,None,A,1438776649,301268696,39.469355,-74.633759
1776,34003,"POLYGON ((-74.24853 40.99209, -74.24860 40.992...",34,003,00882271,34003,Bergen,Bergen County,06,H1,G4020,408,35620,35614,A,602911111,35354979,40.959699,-74.074727
1777,34005,"POLYGON ((-74.89915 40.07321, -74.89879 40.073...",34,005,00882272,34005,Burlington,Burlington County,06,H1,G4020,428,37980,15804,A,2070157741,54113400,39.875786,-74.663006
1778,34007,"POLYGON ((-75.12889 39.90745, -75.12867 39.908...",34,007,00882273,34007,Camden,Camden County,06,H1,G4020,428,37980,15804,A,573293905,15720557,39.802407,-74.961249
1779,34009,"POLYGON ((-74.59880 39.30520, -74.59739 39.306...",34,009,00882274,34009,Cape May,Cape May County,06,H1,G4020,428,36140,None,A,651338862,955248161,39.085841,-74.846354
1780,34011,"POLYGON ((-75.41119 39.42042, -75.41116 39.420...",34,011,00882275,34011,Cumberland,Cumberland County,06,H1,G4020,428,47220,None,A,1251898273,503713107,39.328434,-75.121628
1781,34013,"POLYGON ((-74.32916 40.83856, -74.32899 40.839...",34,013,00882276,34013,Essex,Essex County,06,H1,G4020,408,35620,35084,A,326557454,8638174,40.787400,-74.246292
1782,34015,"POLYGON ((-75.34581 39.84437, -75.34573 39.844...",34,015,00882277,34015,Gloucester,Gloucester County,06,H1,G4020,428,37980,15804,A,833916105,38320616,39.722875,-75.145679
1783,34017,"POLYGON ((-74.09079 40.76198, -74.09027 40.761...",34,017,00882278,34017,Hudson,Hudson County,06,H1,G4020,408,35620,35614,A,119640830,41958705,40.731375,-74.078601
1784,34019,"POLYGON ((-75.11001 40.63891, -75.10989 40.639...",34,019,00882228,34019,Hunterdon,Hunterdon County,06,H1,G4020,408,35620,35084,A,1108076939,24770921,40.565283,-74.911969
1785,34021,"POLYGON ((-74.85665 40.27765, -74.85687 40.278...",34,021,00882229,34021,Mercer,Mercer County,06,H1,G4020,408,45940,None,A,581297755,11434826,40.282503,-74.703724
1786,34023,"POLYGON ((-74.46695 40.50890, -74.46708 40.508...",34,023,00882230,34023,Middlesex,Middlesex County,06,H1,G4020,408,35620,35154,A,800864377,35466050,40.439621,-74.407430
1787,34025,"POLYGON ((-74.32738 40.34460, -74.32701 40.344...",34,025,00882910,34025,Monmouth,Monmouth County,06,H1,G4020,408,35620,35154,A,1212585319,510987402,40.287048,-74.152446
1788,34027,"POLYGON ((-74.65386 40.92632, -74.65411 40.926...",34,027,00882231,34027,Morris,Morris County,06,H1,G4020,408,35620,35084,A,1193878537,53263498,40.858896,-74.547292
1789,34029,"POLYGON ((-74.46955 40.12859, -74.46952 40.128...",34,029,00882279,34029,Ocean,Ocean County,06,H1,G4020,408,35620,35154,A,1627387052,742027591,39.865669,-74.258864
1790,34031,"POLYGON ((-74.25483 40.88307, -74.25505 40.883...",34,031,00882232,34031,Passaic,Passaic County,06,H1,G4020,408,35620,35614,A,481767296,32057602,41.037890,-74.298280
1791,34033,"POLYGON ((-75.51287 39.57836, -75.51291 39.578...",34,033,00882233,34033,Salem,Salem County,06,H1,G4020,428,37980,48864,A,859517464,105387382,39.573828,-75.357356
1792,34035,"POLYGON ((-74.70270 40.62112, -74.70273 40.621...",34,035,00882234,34035,Somerset,Somerset County,06,H1,G4020,408,35620,35154,A,781830431,7994903,40.565527,-74.619938
1793,34037,"POLYGON ((-74.93933 41.06918, -74.94004 41.069...",34,037,00882236,34037,Sussex,Sussex County,06,H1,G4020,408,35620,35084,A,1343564828,43222888,41.137461,-74.691914
1794,34039,"POLYGON ((-74.42857 40.69911, -74.42849 40.699...",34,039,00882235,34039,Union,Union County,06,H1,G4020,408,35620,35084,A,266163527,7053423,40.659871,-74.308696
1795,34041,"POLYGON ((-75.05145 40.86421, -75.05142 40.864...",34,041,00882237,34041,Warren,Warren County,06,H1,G4020,None,10900,None,A,923424386,15834476,40.853491,-75.009498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,36059,"POLYGON ((-73.69445 40.90305, -73.62815 40.941...",36,059,00974128,36059,Nassau,Nassau County,06,H1,G4020,408,35620,35004,A,737195890,437275916,40.729612,-73.589414
1857,36063,"POLYGON ((-79.07585 43.27017, -79.08562 43.284...",36,063,00974130,36063,Niagara,Niagara County,06,H1,G4020,160,15380,None,A,1352887561,1598842375,43.456731,-78.792142
1858,36065,"POLYGON ((-75.86293 43.31922, -75.86293 43.319...",36,065,00974131,36065,Oneida,Oneida County,06,H1,G4020,None,46540,None,A,3139921947,117357163,43.242727,-75.434282
1859,36067,"POLYGON ((-76.47187 43.10706, -76.47189 43.107...",36,067,00974132,36067,Onondaga,Onondaga County,06,H1,G4020,532,45060,None,A,2016013104,70527533,43.006516,-76.196134
1860,36069,"POLYGON ((-77.48252 42.94316, -77.48257 42.944...",36,069,00974133,36069,Ontario,Ontario County,06,H1,G4020,464,40380,None,A,1668081009,47854414,42.856358,-77.303497
1861,36071,"POLYGON ((-74.52975 41.50239, -74.52733 41.502...",36,071,00974134,36071,Orange,Orange County,06,H1,G4020,408,39100,None,A,2103886749,68105750,41.402410,-74.306252
1862,36073,"POLYGON ((-78.46643 43.30277, -78.46640 43.305...",36,073,00974135,36073,Orleans,Orleans County,06,H1,G4020,464,40380,None,A,1013366843,1103741897,43.502287,-78.229726
1863,36075,"POLYGON ((-76.61759 43.42388, -76.62522 43.500...",36,075,00974136,36075,Oswego,Oswego County,06,H1,G4020,532,45060,None,A,2464751381,933476015,43.461443,-76.209262
1864,36077,"POLYGON ((-75.32880 42.65475, -75.32879 42.654...",36,077,00974137,36077,Otsego,Otsego County,06,H1,G4020,None,36580,None,A,2594487145,36314099,42.629776,-75.028841
1865,36079,"POLYGON ((-73.83836 41.49813, -73.83706 41.498...",36,079,00974138,36079,Putnam,Putnam County,06,H1,G4020,408,35620,35614,A,596542964,41243959,41.427907,-73.743861
1866,36083,"POLYGON ((-73.45059 42.94458, -73.44987 42.944...",36,083,00974140,36083,Rensselaer,Rensselaer County,06,H1,G4020,104,10580,None,A,1689852106,33533280,42.710421,-73.513845
1867,36087,"POLYGON ((-74.09884 41.24080, -74.09829 41.241...",36,087,00974142,36087,Rockland,Rockland County,06,H1,G4020,408,35620,35614,A,449218387,66842906,41.154628,-74.024662
1868,36089,"POLYGON ((-74.93945 44.98442, -74.93447 44.984...",36,089,00977309,36089,St. Lawrence,St. Lawrence County,06,H1,G4020,None,36300,None,A,6939877189,367298360,44.488112,-75.074311
1869,36091,"POLYGON ((-74.12434 43.15390, -74.12457 43.155...",36,091,00974143,36091,Saratoga,Saratoga County,06,H1,G4020,104,10580,None,A,2097879145,87573063,43.106135,-73.855387
1870,36093,"POLYGON ((-73.90678 42.76343, -73.90928 42.763...",36,093,00974144,36093,Schenectady,Schenectady County,06,H1,G4020,104,10580,None,A,529862595,12594061,42.817552,-74.043559
1871,36095,"POLYGON ((-74.63065 42.62677, -74.63092 42.627...",36,095,00974145,36095,Schoharie,Schoharie County,06,H1,G4020,104,10580,None,A,1610503569,11676951,42.591294,-74.438172
1872,36097,"POLYGON ((-76.73391 42.29372, -76.73392 42.293...",36,097,00974146,36097,Schuyler,Schuyler County,06,H1,G4020,None,None,None,A,850405405,36246373,42.419776,-76.938603
1873,36099,"POLYGON ((-76.96356 42.94650, -76.96357 42.946...",36,099,00974147,36099,Seneca,Seneca County,06,H1,G4020,464,42900,None,A,838403628,172828921,42.782294,-76.827088
1874,36101,"POLYGON ((-77.42309 42.57664, -77.42237 42.576...",36,101,00974148,36101,Steuben,Steuben County,06,H1,G4020,236,18500,None,A,3601520291,35040141,42.266725,-77.385525
1875,36103,"POLYGON ((-72.86371 41.11338, -72.86351 41.113...",36,103,00974149,36103,Suffolk,Suffolk County,06,H1,G4020,408,35620,35004,A,2361568402,3784825485,40.943554,-72.692218
1876,36105,"POLYGON ((-75.05413 41.73010, -75.05427 41.731...",36,105,00974150,36105,Sullivan,Sullivan County,06,H1,G4020,None,None,None,A,2507463739,74034521,41.719993,-74.771577
1877,36107,"POLYGON ((-76.24726 42.33432, -76.24729 42.334...",36,107,00974151,36107,Tioga,Tioga County,06,H1,G4020,None,13780,None,A,1343194530,11058001,42.178056,-76.297456
1878,36109,"POLYGON ((-76.58599 42.54991, -76.58654 42.550...",36,109,00974152,36109,Tompkins,Tompkins County,06,H1,G4020,296,27060,None,A,1229314959,43787671,42.453006,-76.473484
1879,36111,"POLYGON ((-74.67402 41.97167, -74.68567 41.976...",36,111,00974153,36111,Ulster,Ulster County,06,H1,G4020,408,28740,None,A,2911757960,94596776,41.947212,-74.265458
1880,36113,"POLYGON ((-74.18255 43.52088, -74.18548 43.540...",36,113,00974154,36113,Warren,Warren County,06,H1,G4020,104,24020,None,A,2246082355,166754989,43.555105,-73.838139
1881,36115,"POLYGON ((-73.48391 43.69062, -73.48404 43.690...",36,115,00974155,36115,Washington,Washington County,06,H1,G4020,104,24020,None,A,2152713603,38126958,43.312377,-73.439428
1882,36117,"POLYGON ((-77.37331 43.12341, -77.37348 43.127...",36,117,00974156,36117,Wayne,Wayne County,06,H1,G4020,464,40380,None,A,1563912968,2018185132,43.458758,-77.063164
1883,36119,"POLYGON ((-73.90928 41.16439, -73.91168 41.167...",36,119,00974157,36119,Westchester,Westchester County,06,H1,G4020,408,35620,35614,A,1115219580,179756608,41.152686,-73.745753
1884,36121,"POLYGON ((-78.46380 42.69392, -78.46384 42.697...",36,121,00974158,36121,Wyoming,Wyoming County,06,H1,G4020,None,None,None,A,1535219547,9158065,42.701363,-78.228567
1885,36123,"POLYGON ((-77.12322 42.76172, -77.12315 42.763...",36,123,00974159,36123,Yates,Yates County,06,H1,G4020,464,40380,None,A,875801459,97489006,42.638237,-77.104324

In [59]:
class PopulationData:
    def __init__(
        self,
        path: str = "https://www.ers.usda.gov/webdocs/DataFiles/48747/PopulationEstimates.csv?v=3011.3",
    ):
        self.df = pd.read_csv(path, encoding="cp1251",)

        # FILTER OUT STATES AND US POPULATIONS
        self.df = self.df.loc[self.df["Rural-urban_Continuum Code_2003"].notnull()]

        # CONVIRT FIPS INTS TO 5-DIGIT CODES
        self.df.loc[:, "FIPS"] = self.df.loc[:, "FIPS"].apply(clean_fips)
        self.df.rename(columns={"FIPS": "fips"}, inplace=True)
        self.df.loc[:, "fips"] = self.df.fips.apply(
            lambda x: "00000" if x in NYC_FIPS else x
        )

        self.df = self.df.loc[:, ["POP_ESTIMATE_2018", "fips"]].copy()
        self.df.loc[:, "POP_ESTIMATE_2018"] = self.df["POP_ESTIMATE_2018"].apply(
            lambda x: int(x.replace(",", ""))
        )
        # MAKE NYC GEOGRAPHY a total of 8million plus
        self.df = self.df.groupby("fips").sum().reset_index()

In [ ]:
shapefiles = {
    "tristate": [
        CountyShapeFiles().fil.loc[shapefile.STATEFP.isin(TRI_STATE)],
        state_shapefile.loc[state_shapefile.STATEFP.isin(TRI_STATE)],
    ],
    "us": [shapefile, state_shapefile],
    "northeast": [
        shapefile.loc[shapefile.STATEFP.isin(NORTH_EAST)],
        state_shapefile.loc[state_shapefile.STATEFP.isin(NORTH_EAST)],
    ],
}

In [58]:
StateShapeFile().filter_geography(state_fp_list=NORTH_EAST)

,REGION,DIVISION,STATEFP,STATENS,GEOID,STUSPS,NAME,LSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
5,1,1,44,01219835,44,RI,Rhode Island,00,G4000,A,2677787140,1323663210,41.597419,-71.527272,"MULTIPOLYGON (((-71.78970 41.72520, -71.78971 ..."
7,1,1,33,01779794,33,NH,New Hampshire,00,G4000,A,23189198255,1026903434,43.672691,-71.584315,"POLYGON ((-72.32990 43.60021, -72.32984 43.600..."
9,1,1,50,01779802,50,VT,Vermont,00,G4000,A,23874197924,1030383955,44.068577,-72.669184,"POLYGON ((-73.31328 44.26413, -73.31274 44.265..."
10,1,1,09,01779780,09,CT,Connecticut,00,G4000,A,12542497381,1815617293,41.579864,-72.746657,"POLYGON ((-73.51808 41.66672, -73.51807 41.666..."
14,1,2,34,01779795,34,NJ,New Jersey,00,G4000,A,19048848841,3543837357,40.107274,-74.665201,"POLYGON ((-75.18960 40.59178, -75.18977 40.592..."
18,1,2,42,01779798,42,PA,Pennsylvania,00,G4000,A,115880457407,3398574954,40.904601,-77.827530,"POLYGON ((-80.51935 41.84956, -80.51938 41.850..."
37,1,1,23,01779787,23,ME,Maine,00,G4000,A,79887659040,11745717739,45.409284,-68.666616,"POLYGON ((-70.98912 43.79211, -70.98913 43.792..."
38,1,2,36,01779796,36,NY,New York,00,G4000,A,122050000805,19246143659,42.913397,-75.596272,"MULTIPOLYGON (((-79.31214 42.68680, -79.24977 ..."
51,1,1,25,00606926,25,MA,Massachusetts,00,G4000,A,20204387828,7130663019,42.156520,-71.489592,"POLYGON ((-71.49826 42.01727, -71.49907 42.017..."

In [34]:
class Covid:
    def __init__(
        self,
        path: str = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv",
    ):
        logging.info("Downloading")
        self.df = pd.read_csv(path)

        self.df.loc[:, "fips"] = self.df["fips"].apply(clean_fips)
        self.df.loc[self.df["county"] == "New York City", "fips"] = "00000"

    def merge_population(self):

        self.df = self.df.merge(PopulationData().df, how="left", on="fips")
        self.df.loc[:, "cases_per_100000"] = (
            self.df.cases / self.df.POP_ESTIMATE_2018 * 100000
        )
        self.df.loc[:, "deaths_per_100000"] = (
            self.df.deaths / self.df.POP_ESTIMATE_2018 * 100000
        )

        return self.df

In [62]:
Covid().merge_population()

,date,county,state,fips,cases,deaths,POP_ESTIMATE_2018,cases_per_100000,deaths_per_100000
0,2020-01-21,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
1,2020-01-22,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
2,2020-01-23,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
3,2020-01-24,Cook,Illinois,17031,1,0,5180493.0,0.019303,0.000000
4,2020-01-24,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
5,2020-01-25,Orange,California,06059,1,0,3185968.0,0.031388,0.000000
6,2020-01-25,Cook,Illinois,17031,1,0,5180493.0,0.019303,0.000000
7,2020-01-25,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
8,2020-01-26,Maricopa,Arizona,04013,1,0,4410824.0,0.022672,0.000000
9,2020-01-26,Los Angeles,California,06037,1,0,10105518.0,0.009896,0.000000
10,2020-01-26,Orange,California,06059,1,0,3185968.0,0.031388,0.000000
11,2020-01-26,Cook,Illinois,17031,1,0,5180493.0,0.019303,0.000000
12,2020-01-26,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
13,2020-01-27,Maricopa,Arizona,04013,1,0,4410824.0,0.022672,0.000000
14,2020-01-27,Los Angeles,California,06037,1,0,10105518.0,0.009896,0.000000
15,2020-01-27,Orange,California,06059,1,0,3185968.0,0.031388,0.000000
16,2020-01-27,Cook,Illinois,17031,1,0,5180493.0,0.019303,0.000000
17,2020-01-27,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
18,2020-01-28,Maricopa,Arizona,04013,1,0,4410824.0,0.022672,0.000000
19,2020-01-28,Los Angeles,California,06037,1,0,10105518.0,0.009896,0.000000
20,2020-01-28,Orange,California,06059,1,0,3185968.0,0.031388,0.000000
21,2020-01-28,Cook,Illinois,17031,1,0,5180493.0,0.019303,0.000000
22,2020-01-28,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
23,2020-01-29,Maricopa,Arizona,04013,1,0,4410824.0,0.022672,0.000000
24,2020-01-29,Los Angeles,California,06037,1,0,10105518.0,0.009896,0.000000
25,2020-01-29,Orange,California,06059,1,0,3185968.0,0.031388,0.000000
26,2020-01-29,Cook,Illinois,17031,1,0,5180493.0,0.019303,0.000000
27,2020-01-29,Snohomish,Washington,53061,1,0,814901.0,0.122714,0.000000
28,2020-01-30,Maricopa,Arizona,04013,1,0,4410824.0,0.022672,0.000000
29,2020-01-30,Los Angeles,California,06037,1,0,10105518.0,0.009896,0.000000
...,...,...,...,...,...,...,...,...,...
70188,2020-04-18,Vilas,Wisconsin,55125,4,0,21938.0,18.233203,0.000000
70189,2020-04-18,Walworth,Wisconsin,55127,89,4,103718.0,85.809599,3.856611
70190,2020-04-18,Washburn,Wisconsin,55129,1,0,15878.0,6.298022,0.000000
70191,2020-04-18,Washington,Wisconsin,55131,82,3,135693.0,60.430531,2.210873
70192,2020-04-18,Waukesha,Wisconsin,55133,259,11,403072.0,64.256510,2.729041
70193,2020-04-18,Waupaca,Wisconsin,55135,4,1,51128.0,7.823502,1.955875
70194,2020-04-18,Waushara,Wisconsin,55137,2,0,24263.0,8.243004,0.000000
70195,2020-04-18,Winnebago,Wisconsin,55139,38,1,171020.0,22.219623,0.584727
70196,2020-04-18,Wood,Wisconsin,55141,2,0,73055.0,2.737663,0.000000
70197,2020-04-18,Albany,Wyoming,56001,6,0,38601.0,15.543639,0.000000
70198,2020-04-18,Big Horn,Wyoming,56003,1,0,11881.0,8.416800,0.000000
70199,2020-04-18,Campbell,Wyoming,56005,13,0,46140.0,28.175119,0.000000
70200,2020-04-18,Carbon,Wyoming,56007,4,0,14971.0,26.718322,0.000000
70201,2020-04-18,Converse,Wyoming,56009,8,0,13640.0,58.651026,0.000000
70202,2020-04-18,Crook,Wyoming,56011,4,0,7450.0,53.691275,0.000000
70203,2020-04-18,Fremont,Wyoming,56013,47,0,39531.0,118.894033,0.000000
70204,2020-04-18,Goshen,Wyoming,56015,3,0,13376.0,22.428230,0.000000
70205,2020-04-18,Hot Springs,Wyoming,56017,2,0,4555.0,43.907794,0.000000
70206,2020-04-18,Johnson,Wyoming,56019,11,1,8460.0,130.023641,11.820331
70207,2020-04-18,Laramie,Wyoming,56021,70,1,98976.0,70.724216,1.010346
70208,2020-04-18,Lincoln,Wyoming,56023,5,0,19434.0,25.728105,0.000000
70209,2020-04-18,Natrona,Wyoming,56025,38,0,79115.0,48.031347,0.000000
70210,2020-04-18,Niobrara,Wyoming,56027,1,0,2388.0,41.876047,0.000000
70211,2020-04-18,Park,Wyoming,56029,1,0,29324.0,3.410176,0.000000
70212,2020-04-18,Sheridan,Wyoming,56033,12,0,30233.0,39.691728,0.000000
70213,2020-04-18,Sublette,Wyoming,56035,1,0,9813.0,10.190564,0.000000
70214,2020-04-18,Sweetwater,Wyoming,56037,10,0,43051.0,23.228264,0.000000
70215,2020-04-18,Teton,Wyoming,56039,62,0,23081.0,268.619211,0.000000
70216,2020-04-18,Uinta,Wyoming,56041,6,0,20299.0,29.558106,0.000000
70217,2020-04-18,Washakie,Wyoming,56043,4,0,7885.0,50.729233,0.000000

In [ ]:
TRI_STATE = ["09", "34", "36"]
NORTH_EAST = ["25", "00", "33", "34", "36", "42", "50", "09", "23", "44"]

shapefiles = {
    "tristate": [
        shapefile.loc[shapefile.STATEFP.isin(TRI_STATE)],
        state_shapefile.loc[state_shapefile.STATEFP.isin(TRI_STATE)],
    ],
    "us": [shapefile, state_shapefile],
    "northeast": [
        shapefile.loc[shapefile.STATEFP.isin(NORTH_EAST)],
        state_shapefile.loc[state_shapefile.STATEFP.isin(NORTH_EAST)],
    ],
}

In [25]:
df = Covid().merge_population()

In [24]:
df

             date      county       state   fips  cases  deaths
0      2020-01-21   Snohomish  Washington  53061      1       0
1      2020-01-22   Snohomish  Washington  53061      1       0
2      2020-01-23   Snohomish  Washington  53061      1       0
3      2020-01-24        Cook    Illinois  17031      1       0
4      2020-01-24   Snohomish  Washington  53061      1       0
...           ...         ...         ...    ...    ...     ...
67451  2020-04-17    Sublette     Wyoming  56035      1       0
67452  2020-04-17  Sweetwater     Wyoming  56037     10       0
67453  2020-04-17       Teton     Wyoming  56039     61       0
67454  2020-04-17       Uinta     Wyoming  56041      6       0
67455  2020-04-17    Washakie     Wyoming  56043      4       0

[67456 rows x 6 columns]

In [18]:
class Data:
    def trade_df(self):
        # This method should handle the import of source data
        data = StringIO()

        s = """
        Account|Stock_Code|BuySell|Date|Quantity|Unit_Price
        1001|001|B|20190105|8|2
        1001|002|B|20190105|4|3
        1001|002|S|20190106|3|1
        1001|003|B|20190106|6|5
        1001|003|S|20190106|4|6
        1001|001|S|20190107|6|3
        1002|001|B|20190105|6|2
        1002|002|B|20190105|8|3
        1002|002|S|20190106|3|1
        1002|003|B|20190106|5|5
        1002|003|S|20190106|4|6
        1002|001|S|20190107|6|3
        """

        data.write(s.replace(" ", ""))
        data.seek(0)
        df = pd.read_csv(
            data,
            sep="|",
            dtype={"Account": str, "Date": str, "Stock_Code": str, "Date": str},
        )
        df.Date = pd.to_datetime(df.Date, format="%Y%m%d")
        return df

    def account_df(self):
        data = StringIO()

        s = """
        Account|Name
        1001|David
        1002|Tom
        """

        data.write(s.replace(" ", ""))
        data.seek(0)
        df = pd.read_csv(data, sep="|", dtype={"Account": str, "Name": str})
        return df

    def stock_prices(self):

        data = StringIO()

        s = """
        Stock_Code|Closing_Price|Date
        001|2|20190105
        001|3|20190106
        001|2|20190107
        002|2|20190105
        002|3|20190106
        002|5|20190107
        003|5|20190105
        003|6|20190106
        003|7|20190107
        """

        data.write(s.replace(" ", ""))
        data.seek(0)
        df = pd.read_csv(data, sep="|", dtype={"Stock_Code": str, "Date": str})
        df.Date = pd.to_datetime(df.Date, format="%Y%m%d")
        return df

In [19]:
class Book:
    def __init__(self):
        self._data = Data()

    @property
    def trade_book_df(self):
        if not hasattr(self, "_trade_book_df"):
            df = self._data.trade_df().join(
                self._data.account_df().set_index("Account"), on="Account"
            )
            df["Trade_Amount"] = df.Quantity * df.Unit_Price
            self._trade_book_df = df
        return self._trade_book_df

    def stock_prices(self, date=None):
        df = self._data.stock_prices()
        if date:
            df = df[df.Date == date]
        return df

    @property
    def holdings(self):
        return Holdings(self)

    @property
    def accounts(self):
        return Accounts(self.holdings)


Book().trade_book_df

,Account,Stock_Code,BuySell,Date,Quantity,Unit_Price,Name,Trade_Amount
0,1001,001,B,2019-01-05,8,2,David,16
1,1001,002,B,2019-01-05,4,3,David,12
2,1001,002,S,2019-01-06,3,1,David,3
3,1001,003,B,2019-01-06,6,5,David,30
4,1001,003,S,2019-01-06,4,6,David,24
5,1001,001,S,2019-01-07,6,3,David,18
6,1002,001,B,2019-01-05,6,2,Tom,12
7,1002,002,B,2019-01-05,8,3,Tom,24
8,1002,002,S,2019-01-06,3,1,Tom,3
9,1002,003,B,2019-01-06,5,5,Tom,25
10,1002,003,S,2019-01-06,4,6,Tom,24
11,1002,001,S,2019-01-07,6,3,Tom,18

In [22]:
class Holdings:
    def __init__(self, book):
        self._book = book

    def holdings_of(self, date):
        trades_df = self._book.trade_book_df
        date_hld_df = trades_df[trades_df.Date <= date]
        date_hld_df["qnt_change"] = (
            date_hld_df["BuySell"].map({"B": 1, "S": -1}) * date_hld_df.Quantity
        )
        hld_df = (
            date_hld_df.groupby(["Account", "Stock_Code"], as_index=False)
            .agg({"qnt_change": sum})
            .rename(columns={"qnt_change": "Holdings"})
        )
        hld_df = hld_df.join(
            self._book.stock_prices(date).set_index("Stock_Code"), on="Stock_Code"
        )
        hld_df["Market_Value"] = hld_df.Closing_Price * hld_df.Holdings
        return hld_df


from datetime import date

Book().holdings.holdings_of(date(2019, 1, 6))

/Users/nate/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and a TypeError will be raised. To retain the current
behavior, convert the 'datetime.date' to a datetime with
'pd.Timestamp'.
  import sys
/Users/nate/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/nate/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:16: FutureWarning: Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and 'the values will not compare equal to the
'datetime.date'. To retain the current behavior, convert the
'datetime.date' to a datetime with 'pd.Timestamp'.
  app.launch_new_instance()

  Account Stock_Code  Holdings  Closing_Price       Date  Market_Value
0    1001        001         8              3 2019-01-06            24
1    1001        002         1              3 2019-01-06             3
2    1001        003         2              6 2019-01-06            12
3    1002        001         6              3 2019-01-06            18
4    1002        002         5              3 2019-01-06            15
5    1002        003         1              6 2019-01-06             6